markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Tomek Rabczak
url: http://ff7f00.com
description: A fantastic blog that is fantastic.
twitter: sigdroid
github: tomekr
gravatar_url: http://gravatar.com/avatar/89deba47c2e80b3d353cba86bb2995dc
